spring:
  application:
    name: user-service

  profiles:
    active: "local"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: ${GOOGLE_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            client-name: ${KAKAO_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: ${NAVER_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: ${GOOGLE_USER_NAME_ATTRIBUTE_NAME}
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE_NAME}
          naver:
            authorization-uri: ${NAVER_AUTHORIZATION_URI}
            token-uri: ${NAVER_TOKEN_URI}
            user-info-uri: ${NAVER_USER_INFO_URI}
            user-name-attribute: ${NAVER_USER_NAME_ATTRIBUTE_NAME}