spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      pool-name: hikari_primary_pool
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: embedded

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 10000

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG